# Generated by Django 4.1.6 on 2023-02-14 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldDisplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charfield', models.CharField(max_length=140)),
                ('unique_together_one', models.CharField(max_length=140, unique=True)),
                ('unique_together_two', models.CharField(max_length=140, unique=True)),
                ('charfield_unique', models.CharField(max_length=140, unique=True)),
                ('textfield', models.TextField()),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('boolean', models.DateTimeField()),
                ('choices', models.CharField(choices=[('nurse', 'Nurse'), ('doctor', 'Doctor')], max_length=20)),
                ('duration', models.DurationField()),
                ('file_field', models.FileField(upload_to='')),
                ('float_field', models.FloatField()),
                ('integer', models.SmallIntegerField()),
                ('email', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('json', models.JSONField()),
                ('url', models.URLField()),
                ('uuid', models.UUIDField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('foreignkey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='foreign', to='blog.fielddisplay')),
                ('many_to_many', models.ManyToManyField(related_name='many', to='blog.fielddisplay')),
            ],
            options={
                'ordering': ['updated'],
                'permissions': [('can_change_created_date', 'Can change created date')],
                'get_latest_by': ['-created'],
                'unique_together': {('unique_together_one', 'unique_together_two')},
            },
        ),
    ]
