# Generated by Django 4.1.7 on 2023-02-15 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_fielddisplay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fielddisplay',
            name='boolean',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddisplay',
            name='charfield',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='fielddisplay',
            name='charfield_unique',
            field=models.CharField(blank=True, max_length=140, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='fielddisplay',
            name='choices',
            field=models.CharField(blank=True, choices=[('nurse', 'Nurse'), ('doctor', 'Doctor')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fielddisplay',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddisplay',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddisplay',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddisplay',
            name='email',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddisplay',
            name='file_field',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='fielddisplay',
            name='float_field',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddisplay',
            name='foreignkey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='foreign', to='blog.fielddisplay'),
        ),
        migrations.AlterField(
            model_name='fielddisplay',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='fielddisplay',
            name='integer',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddisplay',
            name='json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddisplay',
            name='many_to_many',
            field=models.ManyToManyField(blank=True, null=True, related_name='many', to='blog.fielddisplay'),
        ),
        migrations.AlterField(
            model_name='fielddisplay',
            name='textfield',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddisplay',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddisplay',
            name='unique_together_one',
            field=models.CharField(blank=True, max_length=140, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='fielddisplay',
            name='unique_together_two',
            field=models.CharField(blank=True, max_length=140, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='fielddisplay',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddisplay',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielddisplay',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
