# Generated by Django 4.1.7 on 2023-02-15 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_fielddisplay_boolean_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fielddisplay',
            name='many_to_many',
            field=models.ManyToManyField(blank=True, related_name='many', to='blog.fielddisplay'),
        ),
    ]
