version: '3.9'

x-solution-template: &solution-template
  build: ./solution # Build in the context of this directory (meaning: use Dockerfile, .dockerignore etc.)
  volumes:
    - ./solution:/app
    - ignore_volume:/app/.venv
    - ignore_volume:/app/database
  env_file:
    - ./solution/.docker.env
  environment:
    - IS_DOCKER=True

x-clean-template: &clean-template
  build: ./clean # Build in the context of this directory (meaning: use Dockerfile, .dockerignore etc.)
  volumes:
    - ./clean:/app
    - ignore_volume:/app/.venv
    - ignore_volume:/app/db.sqlite3
  env_file:
    - ./clean/.docker.env
  environment:
    - IS_DOCKER=True

services:
  clean:
    <<: *clean-template
    # command: pipenv run gunicorn --reload blog.wsgi:application
    depends_on:
      - clean-db
    ports:
      - '8001:8000' # Quotes are required. django
      - '6001:5678' # Quotes are required. debugpy

  # One off command to setup db when starting 'clean'.
  clean-db:
    <<: *clean-template
    entrypoint: ./entrypoint.sh
    command: 'echo "Database ready. Running server on http://localhost:8001"'

  solution:
    <<: *solution-template
    # command: pipenv run gunicorn --reload blog.wsgi:application
    depends_on:
      - solution-db
    command: pipenv run python manage.py runserver 0.0.0.0:8000
    ports:
      - '8002:8000' # Quotes are required. django
      - '6002:5678' # Quotes are required. debugpy

  # One off command to setup db when starting 'solution'.
  solution-db:
    <<: *solution-template
    entrypoint: ./entrypoint.sh
    command: 'echo "Database ready. Running server on http://localhost:8002"'

volumes:
  ignore_volume:
