version: '3.9'

### Templates ###

x-clean-template: &clean-template
  image: emilte/django-workshop:clean
  volumes:
    - ignore_venv_clean:/app/.venv
    - ./clean:/app
  env_file:
    - ./clean/.docker.env
  environment:
    - IS_DOCKER=yes

x-solution-template: &solution-template
  image: emilte/django-workshop:solution
  volumes:
    - ignore_venv_solution:/app/.venv
    - ignore_static_solution:/app/static
    - ./solution:/app
  env_file:
    - ./solution/.docker.env
  environment:
    - IS_DOCKER=yes

### End: Templates ###

### Services ###

services:
  clean:
    <<: *clean-template
    ports:
      - '8001:8000' # Quotes are required. django
      - '6001:5678' # Quotes are required. debugpy

  solution:
    <<: *solution-template
    # command: pipenv run gunicorn --reload blog.wsgi:application
    ports:
      - '8002:8000' # Quotes are required. django
      - '6002:5678' # Quotes are required. debugpy

### End: Services ###

volumes:
  ignore_venv_clean:
  ignore_venv_solution:
  ignore_static_solution:
