version: '3.9'

### Templates ###

x-clean-template: &clean-template
  image: emilte/django-workshop:clean
  volumes:
    - ./clean:/app
    - ignore_venv_clean:/app/.venv
  env_file:
    - ./clean/.docker.env
  environment:
    - IS_DOCKER=yes

x-solution-template: &solution-template
  image: emilte/django-workshop:solution
  volumes:
    - ./solution:/app
    - ignore_venv_solution:/app/.venv
    - ignore_static_solution:/app/static
  env_file:
    - ./solution/.docker.env
  environment:
    - IS_DOCKER=yes

### End: Templates ###

### Services ###

services:
  clean:
    <<: *clean-template
    depends_on:
      - clean-db
    ports:
      - '8001:8000' # Quotes are required. django
      - '6001:5678' # Quotes are required. debugpy

  # One off command to setup db when starting 'clean'.
  clean-db:
    <<: *clean-template
    entrypoint: ./entrypoint.sh
    command: 'echo "Database ready. Running server on http://localhost:8001"'

  solution:
    <<: *solution-template
    # command: pipenv run gunicorn --reload blog.wsgi:application
    depends_on:
      - solution-db
    command: pipenv run python manage.py runserver 0.0.0.0:8000
    ports:
      - '8002:8000' # Quotes are required. django
      - '6002:5678' # Quotes are required. debugpy

  # One off command to setup db when starting 'solution'.
  solution-db:
    <<: *solution-template
    entrypoint: ./entrypoint.sh
    command: 'echo "Database ready. Running server on http://localhost:8002"'

### End: Services ###

volumes:
  ignore_venv_clean:
  ignore_venv_solution:
  ignore_static_solution:
